# Generated by Django 5.0.2 on 2026-03-22 03:30

import core.constants
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(error_messages={'unique': '该用户名已被使用。'}, help_text='必填。3到150个字符。', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名')),
                ('email', models.EmailField(error_messages={'unique': '该邮箱已被注册。'}, help_text='必填。请输入有效的邮箱地址。', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, error_messages={'unique': '该手机号已被注册。'}, help_text='请输入11位中国手机号。', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('role', models.CharField(choices=[(core.constants.UserRole['STUDENT'], '学生'), (core.constants.UserRole['PARENT'], '家长'), (core.constants.UserRole['TEACHER'], '老师'), (core.constants.UserRole['ADMIN'], '管理员')], default=core.constants.UserRole['STUDENT'], help_text='用户的角色，决定可访问的功能和权限。', max_length=20, verbose_name='用户角色')),
                ('avatar', models.ImageField(blank=True, help_text='用户头像图片，建议尺寸200x200像素。', null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, help_text='简短的个人介绍，最多500个字符。', max_length=500, verbose_name='个人简介')),
                ('date_of_birth', models.DateField(blank=True, help_text='用户的出生日期，格式：YYYY-MM-DD。', null=True, verbose_name='出生日期')),
                ('points', models.PositiveIntegerField(default=0, help_text='用户通过完成任务和活动获得的积分。', verbose_name='积分')),
                ('level', models.PositiveIntegerField(default=1, help_text='用户等级，基于积分自动计算。', verbose_name='等级')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的IP地址。', null=True, verbose_name='最后登录IP')),
                ('last_login_device', models.CharField(blank=True, help_text='用户最后一次登录的设备信息。', max_length=200, null=True, verbose_name='最后登录设备')),
                ('email_verified', models.BooleanField(default=False, help_text='标识用户的邮箱地址是否已经过验证。', verbose_name='邮箱已验证')),
                ('phone_verified', models.BooleanField(default=False, help_text='标识用户的手机号是否已经过验证。', verbose_name='手机号已验证')),
                ('notification_preferences', models.JSONField(default=dict, help_text='用户的通知偏好设置，JSON格式。', verbose_name='通知偏好')),
                ('privacy_settings', models.JSONField(default=dict, help_text='用户的隐私设置，JSON格式。', verbose_name='隐私设置')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', '父亲'), ('mother', '母亲'), ('guardian', '监护人'), ('other', '其他')], default='parent', help_text='家长与学生的关系类型。', max_length=20, verbose_name='关系类型')),
                ('is_primary', models.BooleanField(default=False, help_text='标识是否为学生的主要监护人。', verbose_name='主要监护人')),
                ('can_view_progress', models.BooleanField(default=True, help_text='家长是否可以查看学生的学习进度。', verbose_name='可查看学习进度')),
                ('can_set_tasks', models.BooleanField(default=True, help_text='家长是否可以给学生设置任务。', verbose_name='可设置任务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(limit_choices_to={'role': core.constants.UserRole['PARENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to=settings.AUTH_USER_MODEL, verbose_name='家长')),
                ('student', models.ForeignKey(limit_choices_to={'role': core.constants.UserRole['STUDENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '家庭关系',
                'verbose_name_plural': '家庭关系',
                'db_table': 'accounts_family_relationship',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='登录时使用的IP地址。', verbose_name='IP地址')),
                ('user_agent', models.TextField(help_text='登录时使用的浏览器或设备信息。', verbose_name='用户代理')),
                ('location', models.CharField(blank=True, help_text='根据IP地址推断的地理位置。', max_length=100, null=True, verbose_name='地理位置')),
                ('login_method', models.CharField(choices=[('password', '密码登录'), ('sms', '短信验证码'), ('wechat', '微信登录'), ('other', '其他')], default='password', help_text='用户使用的登录方式。', max_length=20, verbose_name='登录方式')),
                ('success', models.BooleanField(default=True, help_text='标识登录是否成功。', verbose_name='登录成功')),
                ('failure_reason', models.CharField(blank=True, help_text='如果登录失败，记录失败原因。', max_length=100, null=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'accounts_login_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_time', models.PositiveIntegerField(default=0, help_text='用户总学习时间（分钟）。', verbose_name='总学习时间')),
                ('total_homework_count', models.PositiveIntegerField(default=0, help_text='用户完成的作业总数。', verbose_name='总作业数')),
                ('total_exercise_count', models.PositiveIntegerField(default=0, help_text='用户完成的运动次数。', verbose_name='总运动次数')),
                ('achievements_unlocked', models.PositiveIntegerField(default=0, help_text='用户已解锁的成就数量。', verbose_name='已解锁成就数')),
                ('followers_count', models.PositiveIntegerField(default=0, help_text='关注该用户的用户数量。', verbose_name='粉丝数')),
                ('following_count', models.PositiveIntegerField(default=0, help_text='该用户关注的用户数量。', verbose_name='关注数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'accounts_user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['points'], name='accounts_us_points_891fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('points__gte', 0)), name='points_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1)), name='level_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('student')), _negated=True), name='parent_not_equal_student'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrelationship',
            unique_together={('parent', 'student')},
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'created_at'], name='accounts_lo_user_id_392dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['created_at'], name='accounts_lo_created_3d7bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_77db9f_idx'),
        ),
    ]
