# Generated by Django 5.1.7 on 2026-03-22 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年')], default='weekly', max_length=20, verbose_name='分析周期')),
                ('period_start', models.DateField(help_text='分析周期的开始日期', verbose_name='周期开始')),
                ('period_end', models.DateField(help_text='分析周期的结束日期', verbose_name='周期结束')),
                ('total_duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='总时长（分钟）')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='总卡路里')),
                ('total_repetitions', models.PositiveIntegerField(default=0, verbose_name='总重复次数')),
                ('exercise_count', models.PositiveIntegerField(default=0, verbose_name='运动次数')),
                ('average_duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='平均时长（分钟）')),
                ('average_calories', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='平均卡路里')),
                ('consistency_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='坚持率')),
                ('improvement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='进步率')),
                ('strengths', models.TextField(blank=True, help_text='运动的优势分析', max_length=5000, verbose_name='优势分析')),
                ('weaknesses', models.TextField(blank=True, help_text='需要改进的方面', max_length=5000, verbose_name='待改进点')),
                ('recommendations', models.TextField(blank=True, help_text='改进运动的建议', max_length=5000, verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(help_text='被分析的用户', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_analyses', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '运动分析',
                'verbose_name_plural': '运动分析列表',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user', 'analysis_period'], name='exercise_ex_user_id_3e0f0d_idx'), models.Index(fields=['period_start', 'period_end'], name='exercise_ex_period__a2f4a1_idx'), models.Index(fields=['consistency_rate', 'improvement_rate'], name='exercise_ex_consist_1d8e4c_idx')],
                'unique_together': {('user', 'analysis_period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='运动计划的名称', max_length=100, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, help_text='运动计划的详细描述和目标', max_length=1000, verbose_name='计划描述')),
                ('target_duration_minutes', models.PositiveIntegerField(help_text='每次运动的目标时长（分钟）', verbose_name='目标时长（分钟）')),
                ('target_repetitions', models.PositiveIntegerField(default=0, help_text='每次运动的目标重复次数', verbose_name='目标重复次数')),
                ('target_calories', models.DecimalField(decimal_places=2, default=0, max_digits=7, help_text='每次运动的目标卡路里消耗', verbose_name='目标卡路里')),
                ('frequency_per_week', models.PositiveIntegerField(default=3, help_text='每周计划运动的次数', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='每周频率')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='计划开始的日期', verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, help_text='计划结束的日期', null=True, verbose_name='结束日期')),
                ('preferred_time', models.TimeField(blank=True, help_text='偏好的运动时间', null=True, verbose_name='偏好时间')),
                ('is_active', models.BooleanField(default=True, help_text='标记计划是否处于激活状态', verbose_name='是否激活')),
                ('completed_count', models.PositiveIntegerField(default=0, help_text='计划已完成的次数', verbose_name='已完成次数')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='完成率')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(help_text='制定计划的用户', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '运动计划',
                'verbose_name_plural': '运动计划列表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='exercise_ex_user_id_7c2a0c_idx'), models.Index(fields=['start_date', 'end_date'], name='exercise_ex_start_d_6d4c0a_idx'), models.Index(fields=['is_active', 'success_rate'], name='exercise_ex_is_acti_3e2d8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='运动的标题，用于快速识别运动内容', max_length=200, verbose_name='运动标题')),
                ('description', models.TextField(blank=True, help_text='运动的详细描述和目标', max_length=2000, verbose_name='运动描述')),
                ('exercise_type', models.CharField(choices=[('jump_rope', 'JUMP_ROPE'), ('push_up', 'PUSH_UP'), ('sit_up', 'SIT_UP'), ('squat', 'SQUAT'), ('running', 'RUNNING'), ('yoga', 'YOGA'), ('other', 'OTHER')], default='other', help_text='运动的类型，如跳绳、俯卧撑、仰卧起坐等', max_length=50, verbose_name='运动类型')),
                ('duration_seconds', models.PositiveIntegerField(help_text='运动的总时长，单位为秒', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='运动时长（秒）')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='运动的重复次数（如跳绳次数、俯卧撑个数等）', verbose_name='重复次数')),
                ('calories_burned', models.DecimalField(decimal_places=2, default=0, help_text='运动消耗的卡路里（千卡）', max_digits=7, verbose_name='消耗卡路里')),
                ('heart_rate_avg', models.PositiveIntegerField(blank=True, help_text='运动的平均心率（次/分钟）', null=True, verbose_name='平均心率')),
                ('heart_rate_max', models.PositiveIntegerField(blank=True, help_text='运动的最大心率（次/分钟）', null=True, verbose_name='最大心率')),
                ('video_file', models.FileField(blank=True, help_text='运动的视频记录文件', null=True, upload_to='exercise/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'flv', 'wmv'])], verbose_name='运动视频')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='运动地点的纬度', max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='运动地点的经度', max_digits=10, null=True, verbose_name='经度')),
                ('location_name', models.CharField(blank=True, help_text='运动地点的名称（如：健身房、公园等）', max_length=100, verbose_name='地点名称')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='运动开始的时间', verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, help_text='运动结束的时间', null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(help_text='进行运动的用户', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_records', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录列表',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'exercise_type'], name='exercise_ex_user_id_8a2a5f_idx'), models.Index(fields=['started_at', 'ended_at'], name='exercise_ex_started_2e6e4b_idx'), models.Index(fields=['exercise_type', 'duration_seconds'], name='exercise_ex_exercis_9d1e0a_idx')],
            },
        ),
    ]